#!/usr/local/bin/bash

if [ -r "/lib/lsb/init-functions" ]; then
        . /lib/lsb/init-functions
else
        log_success_msg() {
                echo "$@"
        }
        log_warning_msg() {
                echo "$@" >&2
        }
        log_failure_msg() {
                echo "$@" >&2
        }
fi

source /usr/local/lib/frr/frrcommon.sh
/usr/local/lib/frr/watchfrr $(daemon_list)
